version: '3'

services:
  message-service:
    image: message-srevice:latest

  user-service:
    image: user-srevice:latest
    command:
      - "--mysql-address=192.168.0.106"

  user-edge-service:
    image: user-edge-service:latest
    links:
      - user-service
      - message-service
    command:
      - "--redis.address=192.168.1.7"

  course-service:
    image: course-service:latest
    links:
      - user-service
    command:
      - "--mysql.address=192.168.0.106"
      - "--zookeeper.address=192.168.0.106"

  course-edge-service:
      image: course-edge-service:latest
      links:
        - user-edge-service
      command:
        - "--zookeeper.address=192.168.0.106"

  api-gateway-zuul:
    image: api-gateway-zuul:latest
    links:
      - user-edge-service
      - course-edge-service
    ports:
      - 8080:8080