srever:
  name: api-gateway-zuul
  port: 8080

zuul:
  routes:
    course:
      path: /course/**
      url: http://${courseService.address}:8081/course
    user:
      path: /user/**
      url: http://${userService.address}:8082/user