version: '2'

services:
  zk:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zk
    ports:
      - "2181:2181"
    container_name: zookeeper

  # kafka version: 1.1.0
  # scala version: 2.12
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # test(topic) will have 1 partition and 1 replicas
      KAFKA_CREATE_TOPICS: "test-topic:1:1"
    depends_on:
      - zk
    container_name: kafka