server:
  name: course-dubbo-service
  port: ${courseDubboService.port}


spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/db_course
    username: root
    password: a11111
    driver-class-name: com.mysql.cj.jdbc.Driver
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://${zookeeper.address}:2181
    protocol:
      name: dubbo
      port: 20880
      host: 127.0.0.1
    scan: me.qinchao.course

thrift:
  user:
    ip: user-service
    port: 7911
