service:
  name: user-thrift-service
  port: 7910

spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/db_user
    username: root
    password: a111111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL