server:
  name: user-thrift-service
  port: 7911

spring:
  datasource:
    url: jdbc:mysql://${mysql.address}:3306/db_user
    username: root
    password: a11111
    driver-class-name: com.mysql.cj.jdbc.Driver