apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
  name: config-service
spec:
  ports:
    - port: 8766
      protocol: TCP
      targetPort: 8766
  selector:
    app: config-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: hub.qinchao.me/microservice/config-service:latest
        ports:
        - containerPort: 8766