apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
  name: config-service
spec:
  ports:
    - port: 8766
  selector:
    app: config-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
      - name: config-service
        image: harbor.devops.qinchao.me/microservice/config-service:$CI_COMMIT_TAG
        ports:
        - containerPort: 8766
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /health
            port: 8766
          initialDelaySeconds: 20
          periodSeconds: 5