apiVersion: v1
kind: Service
metadata:
  labels:
    app: message-service
  name: message-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: message-service
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: harbor.devops.qinchao.me/microservice/message-service:$CI_COMMIT_TAG
        ports:
        - containerPort: 9090
