server:
  port: 8773

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka

hystrix:
  command:
    default:
        execution:
             timeout:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000

spring:
  application:
    name: eureka-consumer-ribbon-hystrix